name: Keepalive Workflow

on:
  schedule:
    # 每 30 天的午夜 0 点触发一次（在 60 天限制内）
    - cron: '0 0 */30 * *'
  workflow_dispatch: # 允许手动触发

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write # 必须赋予 actions 写入权限才能保活
      contents: write # 允许提交 Dummy Commit 或读取仓库内容（必须！）
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Keepalive Action
        uses: gautamkrishnar/keepalive-workflow@v1
        # 这个 Action 会自动检测仓库活跃度，如果快到期了，它会自动产生一个微小的活跃记录来重置 60 天的时钟